env:
  global:
    - secure: Mhn0q9XXZ+2EqCOUfzBm/PantrBlVgQ4TM5OrA2J/X3qsiAGfNWvVA7TJKsDFy+3KoXHHEqfHGqq2ShwSC39SedJqUYvLiUaDFgz3dajGh1mrNfG3c0StiqkRD2cdRmFRI0e6t0QPvxBVdFPmBgoiNiquzJoSOKl5qqTMGnG83Y=
os:
  - linux
  - osx
language: rust
rust:
  - nightly
  - beta
  - stable
sudo: false
branches:
  only:
    - master
cache:
  directories:
    - $HOME/elfutils
script:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/build_and_run_tests.sh | bash
before_cache:
  - curl -sSLO https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/install_elfutils.sh
  - . install_elfutils.sh
after_success:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/after_success.sh | bash
